import datetime

JWT_EXPIRY = 30  # days to JWT expiry
JWT_TIME_DIFF = datetime.timedelta(days=JWT_EXPIRY)
JWT_ALG = 'HS256'
NUM_HASH_ITERATIONS = 4096
SALT_LENGTH = 128

MAX_PASSWORD_LENGTH = 100
MIN_PASSWORD_LENGTH = 7
