import datetime

JWT_EXPIRY = 30  # days to JWT expiry
JWT_TIME_DIFF = datetime.timedelta(days=JWT_EXPIRY)
JWT_ALG = 'HS256'
NUM_HASH_ITERATIONS = 4096
SALT_LENGTH = 128

MAX_PASSWORD_LENGTH = 100
MIN_PASSWORD_LENGTH = 7

HTTP_STATUS_CODES = {
    'SUCCESS': 200,
    'BAD_REQUEST': 400,
    'UNAUTHORIZED': 401,
    'METHOD_NOT_ALLOWED': 405
}
